{% set name = "cca-bocca" %}
{% set version = "0.5.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/{{ name }}
  patches:
    - configure-input.patch
    - fix-config-sub.patch

requirements:
  build:
    - python <3
  run:
    - python <3
    - cca-babel <2
    - cca-spec-babel
    - ccaffeine

build:
  number: 1
