language: java
os:
- linux
- osx
env:
  global:
  - THIS_PACKAGE=cca-bocca
  - BUILD_STR="dev"
  - TRAVIS_PYTHON_VERSION="2.7"
  - NUMPY_VERSION="1.9"
  - secure: WZVAluOHo3WYq7K+b/raA0pSsC3MgeXD0mVqDXjNEi5ZFWh2JIvPI+UQedREqakdwdk0a4/jjb9bUTVUm16Gk8dPyfGCRkKC57wtDeBJJP8PsLIE12K4TQKJPGAL8iZXYGs6VG/Pg8VcQ3XfCw0x02QCD/1HmlVuRJBKgXaAPLLwEizMeaiCwIF1amSfKlOzxnMEyGICr75oI0HF3Jd0SrXzCyiYMtX8r05dyRjx7fohEYm3HgUfWaItNfMqlH4BBwsfQKWEUKoaBpfI7yuid8wrNV1GxoNIC6IMz0CGbeDJTmyhT2lH/x596GvQjMF5m1wbhAvRvLjalkWKiZKNtaaW4aHQJ+9tf+RkXbnfMu8qq6+KM5WrA6i6I3k9uOL+2urf4wUKOLpklK+vmfM9DP1ngNQWI0hVg8RutX7e0AX/7SbNKg4Ojbn6U3o2criFUoX3BRLeFyNUOCNNBo/4CBawk599w8Dg692ermdKMnYIGSs7SZ5XmNXQ3i13xRkc2kIx3hIYupGn8zFz732poY4igZJyq2g5gj3/X81eog25qxgR0+MGdTp0YXPi5xFhdUqsWCd+YQAaITM4KVPxbHQDRTKX+tD8Lk1FdSNVAeLipoXWQjvjjw9lpMEAIm9fLKaSJ7olQDtCLO21r8DaFG5E6KGhV3okZmWut/oG6D0=
sudo: false
install:
- bash ci/travis/install_python.sh $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
script:
- conda build recipe -c conda-forge -c csdms/channel/dev -c csdms
after_success:
- bash ci/travis/deploy_to_anaconda.sh $THIS_PACKAGE
